import PrimaryHeader from "../src/components/PrimaryHeader";
import styles from "../styles/Home.module.css";
import {
  BudgetInput,
  FloatingButton,
  Input,
  QuantityInput,
} from "../src/components/ui/ui";
import SuccessSlider from "../src/components/SuccessSlider";
import Footer from "../src/components/Footer";
import Head from "next/head";
import { init } from "ityped";
import { useRef, useEffect, useState } from "react";
import Link from "next/link";
import { useTranslation } from "react-i18next";
import axios from "axios";
import { toast, ToastContainer } from "react-toastify";
import { BsGoogle } from "react-icons/bs";

const HomePage = () => {
  const { t } = useTranslation();
  const textRef = useRef();

  const [email, setemail] = useState("");

  const getData = async () => {
    const res = await axios.get("/api/home");
    console.log(res);
  };

  useEffect(() => {
    getData();
    init(textRef.current, {
      showCursor: true,
      backDelay: 1500,
      backSpeed: 40,
      strings: ["Brand owner", "Manufacturer", "Supplier"],
    });
  }, []);

  const addEmail = async (e) => {
    e.preventDefault();
    if (!email) {
      return toast.error("Type a valid email address");
    }
    try {
      const res = await axios.post("/api/email", { email });
      if (res.status == 201) {
        toast.success("Your Email submitted");
        setemail("");
      }
    } catch (error) {
      toast.error(error.response.data.message);
    }
  };

  return (
    <>
      <ToastContainer />
      <PrimaryHeader />
      <Head>
        <title>ImpoNexpo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="http://translate.google.com/translate_a/element.js?cb=loadGoogleTranslate" >
          
function loadGoogleTranslate(){
  new google.translate.TranslateElement("google_translate")
}
        </script> */}
      </Head>

      <div className={styles.container}>
        <div id="google_translate"></div>
        <div className={styles.hero} id="hero">
          <div className={styles.left}>
            <h1> {t("home_heading")} </h1>
            <img src="/images/line.png" alt="" />
            <p>{t("home_hero_text")}</p>
          </div>
          <div className={styles.right}>
            <h2>{t("home_hero_right_heading")}</h2>
            <form className={styles.email} onSubmit={addEmail}>
              <input
                value={email}
                type="email"
                placeholder={t("email_box_text")}
                required={true}
                onChange={(e) => setemail(e.target.value)}
              />
              <button type="submit" onClick={() => addEmail}>
                {" "}
                {t("email_button_text")}{" "}
              </button>
            </form>
          </div>
        </div>

        <div className={styles.signIn}>
          <h2> {t("are_you_a")} </h2>
          <h1>
            <span ref={textRef}> </span> ?
          </h1>
          <img src="/images/line.png" alt="" />
          <p>{t("join_us")}</p>
          <Link href="/manufacturer">
            <button> {t("sign_in")} </button>
          </Link>
        </div>

        <div className={styles.testimonials}>
          <p>{t("an_online_&_offline")}</p>

          <img className={styles.img1} src="/images/dotted3.png" alt="" />
          <img className={styles.img2} src="/images/dotted2.png" alt="" />

          <div className={styles.imagesContainer}>
            <div>
              <div className={styles.imgContainer}>
                <img src="images/overview1.png" alt="" />
                <span>{t("reliable_manufacturer")}</span>
              </div>
              <div className={styles.imgContainer}>
                <img src="images/overview2.png" alt="" />
                <span>{t("solving_language_barrier")} </span>
              </div>

              <div className={styles.imgContainer}>
                <img src="images/overview3.png" alt="" />
                <span>{t("secure_payment")}</span>
              </div>

              <div className={styles.imgContainer}>
                <img src="images/overview4.png" alt="" />
                <span> {t("customer_service")} </span>
              </div>
            </div>

            <div>
              <div className={styles.imgContainer}>
                <img src="images/logistics.jpg" alt="" />
                <span> {t("logistics")} </span>
              </div>
              <div className={styles.imgContainer}>
                <img src="images/overview6.png" alt="" />
                <span> {t("localisation")} </span>
              </div>
            </div>
          </div>
        </div>

        <section className={styles.requirement}>
          <div className={styles.top}>
            <h3>{t("get_in_touch")}</h3>
            <img src="/images/line.png" alt="" />
            <p>{t("we_connect_with_sellers")}</p>
          </div>

          <div className={styles.formContainer}>
            <div className={styles.left}>
              <p>{t("worlds_best")}</p>

              <div>
                <span> {t("industries")} </span>
                <span> {t("categories")} </span>
                <span> {t("duration")} </span>
              </div>
            </div>
            <div className={styles.right}>
              <p> {t("one_request")} </p>
              <Input placeholder={t("please_enter_what_you_are_looking_for")} />

              <div className={styles.inputsContainer}>
                <QuantityInput placeholder={"Enter Quantity"} />
                <BudgetInput placeholder={"Pieces"} />
              </div>

              <div className={styles.checkbox}>
                <input type="checkbox" id="check" />
                <label htmlFor="check">{t("agree_terms")}</label>
              </div>

              <div className={styles.submitButton}>
                <button>
                  {" "}
                  <Link href={"/importer"}>{t("submit_requirement")}</Link>{" "}
                </button>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.success}>
          <h1>{t("success_stories")} !</h1>
          <img src="/images/line.png" alt="" />

          <div className={styles.slider}>
            <SuccessSlider />
          </div>

          <div className={styles.successTestimonials}>
            <div>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum
                iste ratione harum adipisci earum, voluptates beatae nisi
                deleniti enim cumque.
              </p>

              <div className={styles.user}>
                <img src="/images/user2.png" alt="" />
                <span>Md Morsalin alif</span>
              </div>
            </div>
            <div>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum
                iste ratione harum adipisci earum, voluptates beatae nisi
                deleniti enim cumque.
              </p>

              <div className={styles.user}>
                <img src="/images/user1.png" alt="" />
                <span>Md Morsalin alif</span>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.contact}>
          <div className={styles.contactBox}>
            <h1>{t("contact_us")} </h1>
            <img src="/images/line.png" alt="" />

            <div className={styles.contacts}>
              <div>
                <h4> {t("for_developers")} </h4>
                <span>abcd@imponexpo.team</span>
              </div>

              <div className={styles.line}></div>

              <div>
                <h4> {t("for_manufacturers")} </h4>
                <span>abcd@imponexpo.team</span>
              </div>
              <div className={styles.line}></div>
              <div>
                <h4>{t("for_buyers")}</h4>
                <span>abcd@imponexpo.team</span>
              </div>
            </div>
          </div>
        </section>
      </div>
      <Footer />
      <FloatingButton />
    </>
  );
};

export default HomePage;
