import React from "react";
import PrimaryHeader from "../src/components/PrimaryHeader";
import styles from "../styles/Home.module.css";
import { Input } from "../src/components/ui/ui";
import SuccessSlider from "../src/components/SuccessSlider";
import Footer from "../src/components/footer";
import Head from 'next/head'

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PrimaryHeader />
      <div className={styles.container}>
        <div className={styles.hero}>
          <div className={styles.left}>
            <h1>
              Redefining the way <br /> Cross-Border Trade <br /> is done!
            </h1>
            <img src="/images/line.png" alt="" />
            <p>
              We connect People and Businesses with Manufacturers who are
              Trusted, Certified and Secured.
            </p>
          </div>
          <div className={styles.right}>
            <h2>Get an Early Access and Exclusive Benifits</h2>
            <div className={styles.email}>
              <input
                type="text"
                placeholder="Please Email me when it’s ready!l"
              />
              <button>Send !</button>
            </div>
          </div>
        </div>

        <div className={styles.signIn}>
          <h2>Are you a</h2>
          <h1>Brand Owner, Manufacturer or Supplier? </h1>
          <img src="/images/line.png" alt="" />
          <p>
            Join us in the mission to help local suppliers to connect acoss the
            worls and become a part on the thriving economy
          </p>

          <button>Sign Up</button>
        </div>

        <div className={styles.testimonials}>
          <p>
            An Online & Offline <br /> Cross-Border B2B System <br /> that makes
            you <strong>Succeed</strong>!
          </p>

          <img className={styles.img1} src="/images/dotted3.png" alt="" />
          <img className={styles.img2} src="/images/dotted2.png" alt="" />

          <div className={styles.imagesContainer}>
            <div>
              <div className={styles.imgContainer}>
                <img src="images/overview1.png" alt="" />
                <span>Reliable Manufacturer</span>
              </div>
              <div className={styles.imgContainer}>
                <img src="images/overview2.png" alt="" />
                <span>Solving Language Barrier</span>
              </div>

              <div className={styles.imgContainer}>
                <img src="images/overview3.png" alt="" />
                <span>Secure Payment</span>
              </div>

              <div className={styles.imgContainer}>
                <img src="images/overview4.png" alt="" />
                <span>Customer Service</span>
              </div>
            </div>

            <div>
              <div className={styles.imgContainer}>
                <img src="images/overview5.png" alt="" />
                <span>Logistics</span>
              </div>
              <div className={styles.imgContainer}>
                <img src="images/overview6.png" alt="" />
                <span>Localisation</span>
              </div>
            </div>
          </div>
        </div>

        <section className={styles.requirement}>
          <div className={styles.top}>
            <h3>
              Get in touch with Reliable Manufacturers of <br />
              Quality Goods at <span>The Best Prices </span>!
            </h3>
            <img src="/images/line.png" alt="" />
            <p>
              We connect with sellers across the globe to provide services{" "}
              <br /> and goods at the best prices possible{" "}
            </p>
          </div>

          <div className={styles.formContainer}>
            <div className={styles.left}>
              <p>World’s Best Sourcing Platform</p>

              <div>
                <span>100+ Industries</span>
                <span>2200+ Categories</span>
                <span>20h Avg Quotation Duration</span>
              </div>
            </div>
            <div className={styles.right}>
              <p>One Request, Multiple Quotes</p>
              <Input placeholder={"Please enter what you are looking for.."} />

              <div className={styles.inputsContainer}>
                <Input placeholder={"Enter Quantity"} width={"30%"} />
                <Input width={"30%"} placeholder={" Pieces"} />
              </div>

              <div className={styles.checkbox}>
                <input type="checkbox" id="check" />
                <label htmlFor="check">
                  I agree to the Terms and Conditions
                </label>
              </div>

              <div className={styles.submitButton}>
                <button>Submit Requirement</button>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.success}>
          <h1>Success Stories !</h1>
          <img src="/images/line.png" alt="" />

          <div className={styles.slider}>
            <SuccessSlider />
          </div>

          <div className={styles.successTestimonials}>
            <div>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum
                iste ratione harum adipisci earum, voluptates beatae nisi
                deleniti enim cumque.
              </p>

              <div className={styles.user}>
                <img src="/images/user2.png" alt="" />
                <span>Md Morsalin alif</span>
              </div>
            </div>
            <div>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum
                iste ratione harum adipisci earum, voluptates beatae nisi
                deleniti enim cumque.
              </p>

              <div className={styles.user}>
                <img src="/images/user1.png" alt="" />
                <span>Md Morsalin alif</span>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.contact}>
          <div className={styles.contactBox}>
            <h1>Contact Us</h1>
            <img src="/images/line.png" alt="" />

            <div className={styles.contacts}>
              <div>
                <h4> For Investors</h4>
                <span>abcd@imponexpo.team</span>
              </div>

              <div className={styles.line}></div>

              <div>
                <h4> For Manufacturers</h4>
                <span>abcd@imponexpo.team</span>
              </div>
              <div className={styles.line}></div>
              <div>
                <h4>
                  For Buyers/ <br />
                  Costumer Support
                </h4>
                <span>abcd@imponexpo.team</span>
              </div>
            </div>
          </div>
        </section>
      </div>
      <Footer />
    </>
  );
};

export default HomePage;
